---
name: Retreev Runner

on:
  repository_dispatch:
    types:
      - "trigger-heavy-build"

concurrency:
  group: retreev-${{ github.event.client_payload.env_short }}-${{ github.event.client_payload.component }}
  cancel-in-progress: false

jobs:
  deploy:
    uses: retreevhq/retreev/.github/workflows/deploy.backend.yml@main
    with:
      artifact_id: ${{ github.event.client_payload.artifact_id }}
      source_repo: ${{ github.event.client_payload.source_repo }}
      repo_name: ${{ github.event.client_payload.repo_name }}
      short_sha: ${{ github.event.client_payload.short_sha }}
      version: ${{ github.event.client_payload.version }}
      component: ${{ github.event.client_payload.component }}
      inference_protocol_version: ${{ github.event.client_payload.inference_protocol_version }}
      env_name: ${{ github.event.client_payload.env_name }}
      env_short: ${{ github.event.client_payload.env_short }}
      env_tag: ${{ github.event.client_payload.env_tag }}
    secrets: inherit
